/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package robot;
import aos.jack.jak.agent.Agent;

/**
 * 
 */

public class Agente extends aos.jack.jak.agent.Agent {
    private robot.Pintar pev;
    public Agente(java.lang.String nombre)
    {
        super(nombre);
        boolean __b = getAgentType() == robot.Agente.class;
        if (__b) {
            __init1();
            __init2();
        }
        if (__b) 
            startAgent();
    }
    
    public void pintarParte(java.lang.String color)
    {
        postEventAndWait(pev.pintar(color));
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public java.lang.Class getAgentType()
    {
        return robot.Agente.class;
    }
    
    public void __init1()
    {
        super.__init1();
    }
    
    public void __init2()
    {
        super.__init2();
        pev = (robot.Pintar) findEvent("robot.Pintar");
    }
    
    synchronized private void __init_desc()
    {
        addEvent("robot.Pintar",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("robot.Pintar",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addPlan("robot.PintarColorActualEspecificado",0);
        addPlan("robot.PintarCualquierColor",0);
    }
    
    public void init_desc()
    {
        newAgentDesc("Agente");
        super.init_desc();
        __init_desc();
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
    }
    
}
