/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package robot;
import aos.jack.jak.event.BDIGoalEvent;

/**
 * 
 */

public class Pintar extends aos.jack.jak.event.BDIGoalEvent {
    public java.lang.String color;
    private final static java.lang.String[] __eventVariableNames = {
            "color"};
    private final static java.lang.String[] __eventVariableTypes = {
            "String"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public robot.Pintar pintar(java.lang.String c)
    {
        robot.Pintar tmp = new robot.Pintar();
        tmp.init(this);
        return tmp.pintar_body(c);
    }
    
    private robot.Pintar pintar_body(java.lang.String c)
    {
        color = c;
        return this;
    }
    
    public Pintar()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "robot/Pintar.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(color);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
